# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD Pipeline

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  
  #Trigger the workflow on push from the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  #Test's job
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn -B test
      
  #Build's job
  build:
    #Depends on test's job
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
         
  #Sonar's Job
  sonar:
    #Depends on build's job
    needs: build
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Analyze with SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Mamak2020_poc-api-ers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     
  
  #Deploy's job
  deploy:
    #Depends on Sonar's job
    needs: sonar
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: mvn -B package -DskipTests --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v2.3.1
      with:
        name: api-ers
        path: target/*.jar
        
        
    
